anchor_version = "0.23.0"

[features]
seeds = false

[programs.localnet]
pawn_shop = "PawnShop11111111111111111111111111111111112"
faucet = "Faucet11111111111111111111111111111111111112"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external-programs/spl_token_metadata.so"