on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Anchor Test
        uses: ./.github/actions/anchor-test-action
        with:
          workspace_dir: program
